### ISSUE TITLE
Search/Filtering

### ISSUE THREAD

**Issue by justjosias** [samwho/symbol.wtf#16]
As more people request characters, it might make sense to add a search function that quickly filters for characters one might find useful. This can be as simple as searching "tm" for ™ or "c" for © or "!?" for ‽, but it could also have other keywords attached to it, making it easy for people to find their desired symbols without too much hassle.

**Comment by bbailleux** [comment]
Maybe adding a description and / or its UTF-8 name (e.g. see [FileFormat.Info](https://www.fileformat.info))  for each character may help.

That would allow to search for character and to add a description for visually impaired users (with use of `title` or `aria-*` attribute).

**Comment by CatalanCabbage** [comment]
Added a PR for this! Let me know what you think @justjosias @bbailleux 
https://github.com/samwho/symbol.wtf/pull/29
