### ISSUE TITLE
Suggestion: make search function search the whole unicode database

### ISSUE THREAD

**Issue by jribbens** [samwho/symbol.wtf#45]

**Comment by samwho** [comment]
I was wondering when this would come up 😄 

I kinda-sorta don't want to. I built this to be a simple thing that can get me the symbols I most commonly find myself needing. I'm happy to take PRs from folks adding their own bug-bear symbols, but I don't want this to be a full unicode symbol search. Plenty of those exist already, e.g. https://symbl.cc/en/unicode-table/.
