### ISSUE TITLE
Add and move symbols

### ISSUE THREAD

**Issue by technetium** [samwho/symbol.wtf#54]
I'd like the the option for visitors to add symbols and move them and store the symbols and order in local storage. Is somebody working on that already?

**Comment by samwho** [comment]
This crossed my mind a few days ago, but to my knowledge nobody is working on it. I don't plan to add it myself, but I would happily review a PR if it's something you're interested in doing!

The way I'm envisioning this working (after only an hour or so of thinking about it, so feel free to suggest other ideas), is an unobtrusive `+` button next to the search box that pops up a form/modal for adding your own symbols. Custom symbols would then appear first in the list, and be visually distinct from the "default" ones. They would save into local storage and be available on the device you've saved them on. No plans for any auth or cross-device syncing.
